name: 自动构建并部署到阿里云 (前端-Showcase)

on:
  push:
    branches:
      - main
    # 💡 只有当 client 文件夹或此工作流文件变动时才触发，改后端代码不触发前端部署
    paths:
      - 'client/**'
      - '.github/workflows/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 检出源码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.13.0'
          # 💡 指定缓存 client 下的 package-lock.json
          cache: 'npm'
          cache-dependency-path: 'client/package-lock.json'

      - name: 安装依赖与打包
        # 💡 核心：进入 client 目录执行命令
        run: |
          cd client
          npm install
          npm run build

      - name: 部署到阿里云
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # 💡 这里的路径变了，构建产物在 client/dist
          source: 'client/dist/*'
          target: '/var/www/yzdWebsite'
          # 💡 关键：这里要写 2。因为路径是 client/dist/，我们要剥掉这两层目录
          strip_components: 2
          overwrite: true

      - name: 重载 Nginx (可选)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 静态资源更新其实不需要重载 Nginx，除非你改了 Nginx 配置
          script: sudo systemctl reload nginx